### ISSUE TITLE
Reduxロジック関連テストの追加

### ISSUE THREAD

**Issue by bioerrorlog** [Japan-DfinityInfoHub/nft-barter#41]
# 概要・目的
Reduxロジック関連汚テストを追加し、振る舞いを保証する (ことを通じて、メンバーがRedux-toolkitに習熟する)。

# AsIs
- Redux toolkitによるstate管理ロジックに関するテストが存在しない。
- メンバーがRedux toolkitを十分に理解していない。

# ToBe
- Redux toolkitによるstate管理ロジックの挙動がテストで保障されている。
- メンバーがRedux toolkitを十分に理解している。

# タスク

**Comment by bioerrorlog** [comment]
フロントの描画関連のテストはスコープ外。

**Comment by bioerrorlog** [comment]
ただし近年は、Reduxロジック部分を切り離してテストする"isolation-style tests"よりも、ユーザシナリオをテストする"integlation-style tests"の方が推奨される傾向にある模様。

[Guiding Principles - Writing Tests | Redux](https://redux.js.org/usage/writing-tests#guiding-principles)
[Blogged Answers: The Evolution of Redux Testing Approaches](https://blog.isquaredsoftware.com/2021/06/the-evolution-of-redux-testing-approaches/)

**Comment by bioerrorlog** [comment]
Testにおけるimport問題にドハマりしたので一旦pending.
(authSliceの要素を呼び出すテストを実行すると下記エラーが出る)
```sh
 FAIL  src/NFTBarter_assets/src/features/auth/authSlice.test.ts
  ● Test suite failed to run

    SyntaxError: The requested module '@reduxjs/toolkit' does not provide an export named 'createAsyncThunk'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:827:5)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:190:3)
```
